# Generated by Django 2.2 on 2019-04-16 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος παιχνιδιού')),
                ('desc', models.TextField(verbose_name='Περιγραφή')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Έτος έκδοσης')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('url', models.CharField(max_length=255, verbose_name='Ιστότοπος παιχνιδιού')),
                ('image', models.ImageField(default='default.png', upload_to='game_images', verbose_name='Εικόνα παιχνιδιού')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='games.Company', verbose_name='Κατηγορία')),
                ('features', models.ManyToManyField(db_table='game_feature', related_name='games', to='games.Feature', verbose_name='Χαρακτηριστικά')),
                ('genres', models.ManyToManyField(db_table='game_genre', related_name='games', to='games.Genre', verbose_name='Κατηγορίες')),
                ('languages', models.ManyToManyField(db_table='game_language', related_name='games', to='games.Language', verbose_name='Γλώσσες')),
                ('platforms', models.ManyToManyField(db_table='game_platform', related_name='games', to='games.Platform', verbose_name='Πλατφόρμες')),
            ],
            options={
                'verbose_name': 'Παιχνίδι',
                'verbose_name_plural': 'Παιχνίδια',
                'db_table': 'game',
                'ordering': ['title'],
            },
        ),
    ]
