# Generated by Django 2.2 on 2019-04-16 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='game_images', verbose_name='Εικόνα παιχνιδιού')),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='games.Game', verbose_name='Εικόνες')),
            ],
            options={
                'verbose_name': 'Εικόνα',
                'verbose_name_plural': 'Εικόνες',
                'db_table': 'gallery',
            },
        ),
    ]
