# Generated by Django 2.2 on 2019-04-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Game',
            new_name='game',
        ),
    ]
