# Generated by Django 2.2 on 2019-04-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190416_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='games.Game', verbose_name='Παιχνίδι'),
        ),
    ]
