# Generated by Django 2.2 on 2019-04-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20190416_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='games.Company', verbose_name='Εταιρία'),
        ),
    ]
